services:
  dns_seed:
    build:
      context: .
      dockerfile: Dockerfile.dns_seed
    container_name: DNS_SEED
    ports:
      - "58333:58333"
    networks:
      - barbaracoin_net

  node:
    build:
      context: .
      dockerfile: Dockerfile.full_node
    depends_on:
      - dns_seed
    networks:
      - barbaracoin_net
    environment:
      - NODE_NAME=${NODE_NAME:-default_node}
    deploy:
      replicas: ${NODE_COUNT:-3}
    ports:
      - "${START_PORT:-58334}-${END_PORT:-58336}:58333"

networks:
  barbaracoin_net:
    driver: bridge
